### ISSUE TITLE
About Clean Architecture, why does usecase access preferences?

### ISSUE THREAD

**Issue by DJDrama** [philipplackner/CalorieTracker#3]
First of all, no offense.
Really great lecture over all!

How about rather creating datasources, and inject into repositories?
so usecases only have dependency on repository interfaces, and repositories use datasources to get data from preferences.

**Comment by philipplackner** [comment]
Hi!
Yes, you could do that as well :) The preferences interface already serves as some kind of a data source and I see the reasoning behind putting it in a repo. Introduces lots of boilerplate code for our little project here, but if strictly sticking to clean architecture that definitely makes sense, so thanks for the comment :)
